Issue 660: Add missing rust dependency to docker-compose.
Error:

  error: can't find Rust compiler

Repro:

  make build

Root cause:

  https://github.com/docker/compose/issues/8105